### ISSUE TITLE
.gq now "has no whois server"

### ISSUE THREAD

**Issue by nc7s** [rfc1036/whois#173]
```
> whois dominio.gq
The domain you requested is not known in Freenoms database.

This TLD has no whois server.
```

**Comment by egobiah** [comment]
Hello,

It appears that the fqdn of the .gq WHOIS server is valid (whois.dominio.gq.). 
In fact, the fqdn used in this code is the same as the one found in the IANA database: https://www.iana.org/domains/root/db/gq.html

However, the server doesn't seem to return a valid response.
I recommend that you contact the registry in charge of the .gq ccTLD to resolve the issue, it cannot be solved here.

**Comment by nc7s** [comment]
Sure, my bad ;)

**Comment by rfc1036** [comment]
The IANA database can be out of date. The problem here is that .gq was outsourced to Freenom, which has since exited the business of providing throwaway domains to abusers, so I believe that we can safely exclude that they will care about the database being broken.
I would also not hold my breath for the Guinean telecom arranging for a new registry to take over, so this may actually take a while...
